SELECT *
FROM "BRIGHT_TV"."ASAVELA_NGWENYA"."USER_PROFILES";

SELECT COUNT(USERID)
FROM VIEWERSHIP;
 
SELECT * 
FROM VIEWERSHIP
LIMIT 10 ;

-- CHANNELS THAT HAVE THE MOST VIEWERSHIP

SELECT CHANNEL2, 
       COUNT(*) VIEWCOUNT
FROM VIEWERSHIP
GROUP BY CHANNEL2
ORDER BY VIEWCOUNT DESC
LIMIT 10;

-- DEMOGRAPHICS STATISTICS
-- AGE
SELECT  
    CASE 
        WHEN AGE BETWEEN 1 AND 19 THEN 'TEENS AND KIDS(UNDER20)'
        WHEN AGE BETWEEN 20 AND 29 THEN 'YOUTH(20-29)'
        WHEN AGE BETWEEN 30 AND 39 THEN 'ADULTS(30-39)'
        WHEN AGE BETWEEN 40 AND 49 THEN 'MIDDLE AGE(40-49)'
        WHEN AGE > 49 THEN 'OLD PEOPLE(50 UPWARDS)'
        ELSE 'NOT SPECIFIED'
    END AS AGE_GROUPING,
 COUNT(*) AS USERS_BY_AGE
 FROM USER_PROFILES
 GROUP BY AGE_GROUPING
 ORDER BY USERS_BY_AGE DESC;

 -- GROUPING DEMOGRRAPHICS BY GENDER-RACE-PROVINCE
SELECT PROVINCE,
    CASE 
        WHEN GENDER = 'male' AND RACE = 'black' THEN 'BLACK MALE'
        WHEN GENDER = 'male' AND RACE = 'coloured'  THEN 'COLOURED MALES'
        WHEN GENDER = 'male' AND RACE = 'indian_asian' THEN 'INDIAN_ASIAN MALES'
        WHEN GENDER = 'male' AND RACE = 'white' THEN 'WHITE MALES'
        WHEN GENDER = 'male' AND RACE = 'None' THEN 'MALE, RACE NOT DISCLOSED'
        WHEN GENDER = 'female' AND RACE = 'black' THEN 'BLACK FEMALE'
        WHEN GENDER = 'None'  AND RACE = 'None' THEN 'DEMOGRAPHICS UNDISCLOSED'
        WHEN GENDER = 'female' AND RACE = 'coloured' THEN 'COLOURED FEMALE'
        WHEN GENDER = 'female' AND RACE = 'None' THEN 'FEMALE, RACE NOT DISCLOSED'
        WHEN GENDER = 'female' AND RACE = 'white' THEN 'WHITE FEMALE'
        WHEN GENDER = 'male' AND RACE = 'other' THEN 'MALE OTHER'
        WHEN GENDER = 'female' AND RACE = 'indian_asian' THEN 'INDIAN_ASIAN FEMALES'
        WHEN GENDER = 'male' AND RACE IS NULL THEN 'MALE, RACE NULL'
        WHEN GENDER = 'female' AND RACE = 'other' THEN 'FEMALE OTHER'
        WHEN GENDER = 'female' AND RACE IS NULL  THEN 'FEMALE, RACE NULL'
    END AS DEMOGRAPHICS,
        COUNT(*) AS DEMOGRAPHIC_COUNT,
FROM USER_PROFILES UP 
JOIN VIEWERSHIP V
    ON UP.USERID = V.USERID       
GROUP BY PROVINCE, DEMOGRAPHICS
ORDER BY DEMOGRAPHIC_COUNT DESC;


-- LOOKING AT LOCATION

SELECT PROVINCE,
       COUNT(*) AS USER_LOCATION
FROM USER_PROFILES UP
JOIN VIEWERSHIP V
    ON UP.USERID = V.USERID
GROUP BY PROVINCE
ORDER BY USER_LOCATION DESC;

-- PEAK VIEWEING TIME
SELECT MIN(RECORDDATE)
FROM VIEWERSHIP;

SELECT MAX(RECORDDATE)
FROM VIEWERSHIP;

-- PEAK DATE/HOUR
SELECT CHANNEL2,
       DATE_TRUNC('HOUR', DATEADD(HOUR,2,TO_TIMESTAMP(RECORDDATE, 'YYYY/MM/DD HH24:MI'))) AS LOCAL_TIME,
       COUNT(*) VIEWCOUNT
FROM VIEWERSHIP VW
RIGHT JOIN USER_PROFILES UP
GROUP BY CHANNEL2, LOCAL_TIME
ORDER BY VIEWCOUNT DESC
LIMIT 10;
      
-- DOWN TIME (DATE/HOUR) 

SELECT 
       DATE_TRUNC('HOUR', DATEADD(HOUR,2,TO_TIMESTAMP(RECORDDATE, 'YYYY/MM/DD HH24:MI'))) AS LOCAL_TIME,
       COUNT(*) VIEWCOUNT
FROM VIEWERSHIP VW
RIGHT JOIN USER_PROFILES UP
GROUP BY LOCAL_TIME
ORDER BY VIEWCOUNT ASC
LIMIT 10;


-- LONGEST DURATION SESSION 
SELECT NAME,
       SURNAME,
       GENDER,
       RACE,
       AGE,
       CHANNEL2,
       DURATION
FROM VIEWERSHIP VW
JOIN USER_PROFILES UP
    ON VW.USERID = UP.USERID
ORDER BY DURATION DESC
LIMIT 10;









